version: "3.9"

services:
  elasticsearch:
    image: elasticsearch:8.2.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200
    networks:
      - elastic
  kibana:
    image: kibana:8.2.2
    ports:
      - target: 5601
        published: 5601
    depends_on:
      - elasticsearch
    networks:
      - elastic
  postgres:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - target: 5432
        published: 5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres
volumes:
  es_data:
    driver: local
  postgres:
    driver: local
networks:
  elastic:
    name: elastic
    driver: bridge
  postgres:
    name: postgres
    driver: bridge